site_name: SuitUp PHP Framework
theme: readthedocs
  nav:
    - Home: Home.md
    #### Complete Documentation
    - [[1. Install]]  
      - [[1.1 Default Constants]]  
    - [[2. Controllers and Views]]  
      - [[2.1 MvcAbstractController (en)]]  
      - [[2.2 ErrorController (en)]]  
      - [[2.3 Pagination]]  
      - [[2.4 Debug (en)]]  
    - [[3. Layouts (en)]]  
    - [[4. Forms]]  
      - [[4.1 Validations and Filters]]
      - [[4.2 Filters]]
      - [[4.3 Personal Validation]]
      - [[4.4 Personal Filter]]
    - [[5. Database]]  
      - [[5.1 database.config.php (en)]]  
      - [[5.2 SQL Monitoring]]  
    - [[6. Routes]]  
    - [[7. Functions]]

    # Português
    - [[Home]]  
    #### Documentação Completa
    - [[1. Instalação]]  
      - [[1.1 Constantes padrão]]  
    - [[2. Controllers e Views]]  
      - [[2.1 MvcAbstractController]]    
      - [[2.2 ErrorController]]  
      - [[2.3 Paginação]]  
      - [[2.4 Debug]]  
    - [[3. Layouts]]  
    - [[4. Formulários]]  
      - [[4.1 Validações]]
      - [[4.2 Filtros]]
      - [[4.3 Validação Personalizada]]
      - [[4.4 Filtro Personalizado]]
    - [[5. Banco de dados]]  
      - [[5.1 database.config.php]]  
      - [[5.2 Monitoramento de SQL]]  
    - [[6. Rotas]]  
    - [[7. Funções]]
