site_name: Suitup Framework
site_description: Awesome PHP Framework with high productivity
site_author: Braghim Sistemas
repo_name: braghimsistemas/suitup-php
repo_url: https://github.com/braghimsistemas/suitup-php
theme:
  name: material
  palette:
    primary: deep purple
  logo:
    icon: person_pin_circle
  highlightjs: true
  hljs_languages:
    - yaml
    - php
extra_css:
  - css/extra-style.css
nav:
  - Home: index.md
  - User Guide:
    - Getting Started: user-guide/getting-started/index.md
    - Tutorial for impatients: user-guide/getting-started/impatients/index.md
    - Step By Step Tutorial: user-guide/getting-started/from-source/index.md
  - Contributors: contributors/index.md
  - About:
    - License: about/LICENSE.md
    - SuitUp 1 Compatibility: compatibility/index.md
plugins:
  - search
markdown_extensions:
  - admonition
  - codehilite
  - meta
  - toc:
      permalink: true
copyright: Copyright &copy; 2019 Braghim Sistemas
