site_name: Suitup Framework
site_description: Awesome PHP Framework with high productivity
site_author: Braghim Sistemas

repo_url: https://github.com/braghimsistemas/suitup-php

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - php

nav:
    - Introduction: index.md
    - Getting Started: "Getting Started/index.md"
    - SuitUp 1 Compatibility: "SuitUp 1 Compatibility/index.md"

markdown_extensions:
    - def_list

plugins:
    - search
