site_name: Suitup Framework
site_description: Awesome PHP Framework with high productivity
site_author: https://www.thizer.com
site_url: https://suitupframework.com/

repo_name: braghimsistemas/suitup-php
repo_url: https://github.com/braghimsistemas/suitup-php
edit_uri: ""

theme:
  name: material
  feature:
      tabs:
          true
  palette:
    primary: deep purple
  logo:
    icon: person_pin_circle
extra_css:
  - assets/css/extra-style.css
nav:
  - User Guide:
    - Home: index.md
    - Getting Started: user-guide/getting-started/index.md
    - Tutorial for impatients: user-guide/getting-started/impatients.md
    - Step By Step Tutorial: user-guide/getting-started/from-source.md
    - Demo projects: user-guide/demo-projects/index.md
    - Reference documents:
      - Overview: user-guide/reference/overview.md
      - Routes: user-guide/reference/overview.md
      - Controllers & Actions: user-guide/reference/overview.md
      - Abstract Controller: user-guide/reference/abstract-controller.md
      - Error Controller: user-guide/reference/overview.md
      - Modules: user-guide/reference/overview.md
      - Views & Layouts: user-guide/reference/overview.md
      - Models (database):
        - Workflow ((IMPORTANT)): user-guide/reference/overview.md
        - Business: user-guide/reference/overview.md
        - Gateways: user-guide/reference/overview.md
        - Adapters (help wanted): user-guide/reference/overview.md
        - SQL Queries: user-guide/reference/overview.md
        - SQL Monitor: user-guide/reference/overview.md
        - Out of box: user-guide/reference/overview.md
      - Form Validation: user-guide/reference/overview.md
      - Pagination: user-guide/reference/overview.md
      - Functions outstand: user-guide/reference/overview.md
    - Old Version:
      - Português (Brasil):
        - 1. Instalação: user-guide/old-version/ptbr/1.-Instalação.md
        - 1.1 Constantes padrão: user-guide/old-version/ptbr/1.1-Constantes-padrão.md
        - 2. Controllers e Views: user-guide/old-version/ptbr/2.-Controllers-e-Views.md
        - 2.1 MvcAbstractController: user-guide/old-version/ptbr/2.1-MvcAbstractController.md
        - 2.2 ErrorController: user-guide/old-version/ptbr/2.2-ErrorController.md
        - 2.3 Paginação: user-guide/old-version/ptbr/2.3-Paginação.md
        - 2.4 Debug: user-guide/old-version/ptbr/2.4-Debug.md
        - 3. Layouts: user-guide/old-version/ptbr/3.-Layouts.md
        - 4. Formulários: user-guide/old-version/ptbr/4.-Formulários.md
        - 4.1 Validações: user-guide/old-version/ptbr/4.1-Validações.md
        - 4.2 Filtros: user-guide/old-version/ptbr/4.2-Filtros.md
        - 4.3 Validação Personalizada: user-guide/old-version/ptbr/4.3-Validação-Personalizada.md
        - 4.4 Filtro Personalizado: user-guide/old-version/ptbr/4.4-Filtro-Personalizado.md
        - 5. Banco de dados: user-guide/old-version/ptbr/5.-Banco-de-dados.md
        - 5.1 database.config.php: user-guide/old-version/ptbr/5.1-database.config.php.md
        - 5.2 Monitoramento de SQL: user-guide/old-version/ptbr/5.2-Monitoramento-de-SQL.md
        - 6. Rotas: user-guide/old-version/ptbr/6.-Rotas.md
        - 7. Funções: user-guide/old-version/ptbr/7.-Funções.md
      - English:
        - 1. Install: user-guide/old-version/en/1.-Install.md
        - 1.1 Default Constants: user-guide/old-version/en/1.1-Default-Constants.md
        - 2. Controllers and Views: user-guide/old-version/en/2.-Controllers-and-Views.md
        - 2.1 MvcAbstractController: user-guide/old-version/en/2.1-MvcAbstractController.md
        - 2.2 ErrorController: user-guide/old-version/en/2.2-ErrorController.md
        - 2.3 Pagination: user-guide/old-version/en/2.3-Pagination.md
        - 2.4 Debug: user-guide/old-version/en/2.4-Debug.md
        - 3. Layouts: user-guide/old-version/en/3.-Layouts.md
        - 4. Forms: user-guide/old-version/en/4.-Forms.md
        - 4.1 Validation: user-guide/old-version/en/4.1-Validation.md
        - 4.2 Filters: user-guide/old-version/en/4.2-Filters.md
        - 4.3 Personal Validation: user-guide/old-version/en/4.3-Personal-Validation.md
        - 4.4 Personal Filter: user-guide/old-version/en/4.4-Personal-Filter.md
        - 5. Database: user-guide/old-version/en/5.-Database.md
        - 5.1 database.config.php: user-guide/old-version/en/5.1-database.config.php.md
        - 5.2 SQL Monitoring: user-guide/old-version/en/5.2-SQL-Monitoring.md
        - 6. Routes: user-guide/old-version/en/6.-Routes.md
        - 7. Functions: user-guide/old-version/en/7.-Functions.md
  - Troubleshooting:
    - Github Issues: troubleshooting/issues.md
  - Contributors:
    - How to contribute: contributors/index.md
  - About:
    - Overview: about/index.md
    - Comparing to Suitup 1: about/compatibility.md
    - License: about/LICENSE.md
plugins:
  - search
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
      linenums: true
  - meta
  - toc:
      permalink: true
  - pymdownx.superfences

copyright: Copyright &copy; 2019 Braghim Sistemas
google_analytics:
  - 'UA-64023203-5'
  - 'auto'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/braghimsistemas'
    - type: 'youtube'
      link: 'https://www.youtube.com/channel/UCnQKkBQpuqSqTIWN0XGgAlQ'
    - type: 'facebook'
      link: 'https://www.facebook.com/braghimsistemas/'
    - type: 'github'
      link: 'https://github.com/marcobraghim'
    - type: 'github'
      link: 'https://github.com/thizer'
    - type:  'youtube'
      link: 'https://www.youtube.com/channel/UCwoZZYTjG-RsvaQZVTyc_5w'
    - type: 'facebook'
      link: 'https://www.facebook.com/thizer.apps/'
