site_name: Suitup Framework
site_description: Awesome PHP Framework with high productivity
site_author: https://www.thizer.com

repo_name: braghimsistemas/suitup-php
repo_url: https://github.com/braghimsistemas/suitup-php
edit_uri: ""

theme:
  name: material
  feature:
      tabs:
          true
  palette:
    primary: deep purple
  logo:
    icon: person_pin_circle
extra_css:
  - css/extra-style.css
nav:
  - User Guide:
    - Home: index.md
    - Getting Started: user-guide/getting-started/index.md
    - Tutorial for impatients: user-guide/getting-started/impatients.md
    - Step By Step Tutorial: user-guide/getting-started/from-source.md
    - Demo projects: user-guide/demo-projects/index.md
    - Reference documents:
      - Overview: user-guide/reference/overview.md
      - Routes: user-guide/reference/overview.md
      - Controllers & Actions: user-guide/reference/overview.md
      - Abstract Controller: user-guide/reference/overview.md
      - Error Controller: user-guide/reference/overview.md
      - Modules: user-guide/reference/overview.md
      - Views & Layouts: user-guide/reference/overview.md
      - Models (database):
        - Workflow ((IMPORTANT)): user-guide/reference/overview.md
        - Business: user-guide/reference/overview.md
        - Gateways: user-guide/reference/overview.md
        - Adapters (help wanted): user-guide/reference/overview.md
        - SQL Queries: user-guide/reference/overview.md
        - SQL Monitor: user-guide/reference/overview.md
        - Out of box: user-guide/reference/overview.md
      - Form Validation: user-guide/reference/overview.md
      - Pagination: user-guide/reference/overview.md
      - Functions outstand: user-guide/reference/overview.md
  - Troubleshooting:
    - Github Issues: troubleshooting/issues.md
  - Contributors:
    - How to contribute: contributors/index.md
  - About:
    - Overview: about/index.md
    - Comparing to Suitup 1: about/compatibility.md
    - License: about/LICENSE.md
plugins:
  - search
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
      linenums: true
  - meta
  - toc:
      permalink: true
  - pymdownx.superfences

copyright: Copyright &copy; 2019 Braghim Sistemas
google_analytics:
  - 'UA-64023203-5'
  - 'auto'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/braghimsistemas'
    - type: 'youtube'
      link: 'https://www.youtube.com/channel/UCnQKkBQpuqSqTIWN0XGgAlQ'
    - type: 'facebook'
      link: 'https://www.facebook.com/braghimsistemas/'
    - type: 'github'
      link: 'https://github.com/marcobraghim'
    - type: 'github'
      link: 'https://github.com/thizer'
    - type:  'youtube'
      link: 'https://www.youtube.com/channel/UCwoZZYTjG-RsvaQZVTyc_5w'
    - type: 'facebook'
      link: 'https://www.facebook.com/thizer.apps/'
